id = "com.ceiphr.overcast"
github = "ceiphr/sn-overcast-theme"
main = "dist/dist.css"
name = "Overcast"
content_type = "SN|Theme"
version = "1.2.2"
marketing_url = "https://github.com/ceiphr/sn-overcast-theme"
thumbnail_url = "https://i.imgur.com/KDnyBGx.png"
description = "Overcast to become cloudy or dark — just like this theme."

[dock_icon]
type = "circle"
background_color = "#039be5"
foreground_color = "#19181a"
border_color = "#039be5"
